= Messaging API

The following document describes the Messaging API of Barracks.

== Before you start

IMPORTANT: In order to use the endpoints listed in this documentation, you'll have to authenticate your requests with a valid token and prefix each URL with the correct _Base URL_.

=== Authentication
To authenticate a request:

* Use the Authentication API to get a valid token
** You can generate temporary and permanent tokens depending your needs
* Set the _x-auth-token_ header with your token to each of your requests

=== Base URL
If you use the SaaS version of Barracks available on https://app.barracks.io, the _Base URL_ of the Messaging API is https://app.barracks.io/api/messaging. +
If you use an On Premise version of Barracks and you're not sure what your _Base URL_ is, please contact us.

=== Request example
[source,bash]
----
$ curl 'https://app.barracks.io/api/messaging/messages' -H 'Accept: application/json' -H 'x-auth-token:YzEyYThjMi01ODhjLTRie9.eyJqdGkiOiI4yJhbGciOiJIUzUxMiJ...'
----

=== Having difficulties?
If you don't find the endpoint you are looking for or you encounter any issue with that documentation, please mailto:support@barracks.io[let us know]!

include::docs/messages.adoc[]
